### ISSUE TITLE
Bugsnag 3 support

### ISSUE THREAD

**Issue by borantula** [steefaan/cakephp-bugsnag#2]
Hi,

I'd like to use the package but is it supporting Bugsnag 3._, which is the current version now. Composer.json indicates this requires 2._ line, and not installing.

Thanks :)

**Comment by DaVinciEngineer** [comment]
Hi @borantula,

I have recently released `1.0.0` version with the Bugsnag 3 support. Feel free to try it and report any bugs.

Thanks
